foresterre/imagineer

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/tests.rs
> Upgrade image crate

- Cargo.lock
- Cargo.toml
- LICENSE
- RELEASE_STEPS.md
- src/main.rs
- Adds `--license` option
- Fixes version number
- Fixes `--help` text
> CLI license and help text

- README.md
> Remove crop from the to be implemented operations.

- Cargo.lock
- Cargo.toml
- RELEASE_STEPS.md
- TODO.md
- src/main.rs
Completed [release checklist](https://github.com/foresterre/sic/blob/master/RELEASE_STEPS.md) 1-6.
7-10 will be performed from the master branch.
> Prepare release 0.7.0

- Cargo.lock
- Cargo.toml
- src/main.rs
- build.rs replaced cargo make release
> 0.7.1 release

- Cargo.lock
- Cargo.toml
- src/main.rs
> Release 0.7.2

- src/main.rs
See the tracking issue.
---
Issue: #71
> Setup main to be usable in test cases.

- README.md
- src/lib.rs
- tests/cli_convert.rs
> Rename '--force-format' to '--output-format'.

- .travis.yml
It looks like the cache is too large (?). It slows down the CI runs significantly.
> Remove cargo cache from Travis CI.

- Cargo.lock
- src/parser/grammar.pest
- src/parser/parse.rs
Renames setopt to set, instead of creating a syntax separation with setopt and setflag.
fixes #45
> Add ability to preserve aspect ratio on resize.

- Cargo.lock
- src/parser/grammar.pest
- src/parser/parse.rs
Adds a command called 'del', which enables one to unset a specific option.
An option will only be disabled from the 'del' statement onwards, until
it is set again somewhere along the command list.
---
fixes #103
> Adds a command called 'del', which enables one to unset a specific option.

- Cargo.lock
- sic_io/Cargo.toml
- sic_io/src/conversion.rs
- sic_io/src/encoding_format.rs
- sic_io/src/lib.rs
- src/app/run_mode.rs
Increases portability.
closes #134
> Rewrite sic_io to no longer depend on sic_config.

- Cargo.lock
- Cargo.toml
- README.md
- sic_image_engine/src/engine.rs
- sic_image_engine/src/lib.rs
- sic_parser/src/lib.rs
- sic_parser/src/rule_parser.rs
- sic_parser/src/value_parser.rs
- src/app/cli.rs
- src/app/config.rs
- src/app/img_op_arg.rs
- src/app/mod.rs
- src/app/run_mode.rs
- src/lib.rs
- src/main.rs
- tests/cli_convert.rs
- tests/cli_image_operation_args.rs
- tests/cli_input_output.rs
- tests/common/mod.rs
> Add all image operations as cli arguments.

- examples/gen_completions.rs
> Add script to generate completions (in cargo examples folder).

- Cargo.lock
- components/sic_core/Cargo.toml
- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/wrapper/filter_type.rs
- components/sic_io/src/conversion.rs
- components/sic_io/src/format.rs
- components/sic_io/src/load.rs
- components/sic_parser/src/rule_parser.rs
- src/app/procedure.rs
- tests/cli_convert.rs
> Upgrade image crate to 0.23

- Cargo.lock
- components/sic_image_engine/Cargo.toml
- components/sic_image_engine/src/engine.rs
- components/sic_io/Cargo.toml
- components/sic_io/src/format.rs
- components/sic_parser/Cargo.toml
- components/sic_parser/src/value_parser.rs
- components/sic_testing/Cargo.toml
- components/sic_testing/src/lib.rs
- examples/gen_completions.rs
- src/app/cli.rs
- src/app/operations.rs
- tests/cli_convert.rs
- tests/cli_input_output.rs
> Apply Clippy suggestions.

- Cargo.lock
- README.md
- components/sic_cli_ops/src/lib.rs
- components/sic_cli_ops/src/operations.rs
- components/sic_parser/Cargo.toml
- components/sic_parser/src/grammar.pest
- components/sic_parser/src/lib.rs
- components/sic_parser/src/rule_parser.rs
- components/sic_parser/src/value_parser.rs
> Add diff operation to image-script

- src/cli/config.rs
- src/cli/glob_base_dir.rs
- src/cli/mod.rs
Sic does not process directories, so we can skip them.
closes #408
> Skip directories in glob mode

- src/cli/glob_base_dir.rs
> Apply workaround which accept relative paths starting with ./

- .github/workflows/ci.yml
Also preliminarily branch main to the CI
> Update cargo-deny action to v1

- Makefile
- README.md
> Add Makefile for building for MacOS & Linux👷‍♂️

- tasks/publish/src/arguments.rs
- tasks/publish/src/main.rs
- tasks/publish/src/pipeline/commit.rs
- tasks/publish/src/pipeline/mod.rs
- tasks/publish/src/pipeline/tag.rs
> Add option to tag the new workspace version

- Cargo.lock
- Cargo.toml
- components/sic_cli_ops/Cargo.toml
- components/sic_core/Cargo.toml
- components/sic_image_engine/Cargo.toml
- components/sic_io/Cargo.toml
- components/sic_parser/Cargo.toml
- components/sic_testing/Cargo.toml
> release sic 0.15.0

- tools/pack-release/src/actions.rs
- tools/pack-release/src/main.rs
> Generate shell completions after building

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- components/sic_cli_ops/Cargo.toml
- components/sic_core/Cargo.toml
- components/sic_image_engine/Cargo.toml
- components/sic_io/Cargo.toml
- components/sic_parser/Cargo.toml
- components/sic_testing/Cargo.toml
- thanks/licenses.html
- tools/cargo-publish-workspace/Cargo.toml
- tools/pack-release/Cargo.toml
> Release v0.17.0

- CHANGELOG.md
- components/sic_io/src/conversion.rs
- components/sic_io/src/errors.rs
- components/sic_io/src/save.rs
- src/cli/app.rs
- src/cli/config.rs
- src/cli/pipeline/mod.rs
> Add option to set repeat value for gif encoded images

- src/cli/pipeline/mod.rs
> Fix automatic color type adjustment setting was ignored

- CHANGELOG.md
- README.md
- resources/help-pages/image_operations.txt
> Add horizontal-gradient to the docs

- README.md
> published on gentoo linux GURU overlay

- CHANGELOG.md
- README.md
- components/sic_cli_ops/src/operations.rs
- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/lib.rs
- components/sic_image_engine/src/operations/horizontal_gradient.rs
- components/sic_image_engine/src/operations/mod.rs
- components/sic_image_engine/src/operations/vertical_gradient.rs
- components/sic_image_engine/src/wrapper/gradient_fn.rs
- components/sic_image_engine/src/wrapper/mod.rs
- components/sic_parser/src/grammar.pest
- components/sic_parser/src/rule_parser.rs
- resources/help-pages/image_operations.txt
- src/cli/app.rs
Based on horizontal_gradient and generalized the functions which implemented that operation
> Add vertical_gradient image operation

- .github/workflows/ci.yml
Determines whether we can lower, or on build failure, need to increase the MSRV.
> Update workflow run with MSRV

- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/operations/diff.rs
- components/sic_io/src/conversion.rs
- src/cli/app.rs
- src/cli/common_dir.rs
- src/cli/pipeline/mod.rs
- tests/cli_convert.rs
Thanks Clippy!
with: clippy-0.1.54
> Remove needless borrows

- README.md
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. We are now [packaging and distributing imagineer](https://github.com/Homebrew/homebrew-core/pull/235363), and I wanted to open this PR to give users another installation method. Thanks!
> README: Add Homebrew installation instructions
