foresterre/imagineer

- Cargo.toml
- LICENSES_DEPENDENCIES
- RELEASE_STEPS.md
- examples/update_dep_licenses.rs
- resources/credits.txt
- src/main.rs
Should fix #50 by included the licenses in the repo;
Does require a rerun on every release or added dependency.
While almost certain that it fixes #50, this can't be properly tested without releasing it to crates.io, as `cargo install sic` was the only place which produced the error.
> Fix cargo install

- .travis.yml
- Cargo.toml
- src/operations/mod.rs
- src/operations/operations.rs
- src/operations/test_setup.rs
This inverses the 'dont-run-on-ci' feature, by making output of test images for manual
inspection a feature; compared to creating output images from tests for manual inspection by default.
If you want to run tests with manual inspection, now you'll have to run cargo with
'--features output-test-images' explicitly.
> Make image output feature

- Cargo.toml
- src/conversion/mod.rs
- src/main.rs
- src/operations/mod.rs
- src/operations/operations.rs
- src/operations/parse.rs
Update to Rust edition 2018 with `cargo fix`.
[edition guide: transition](https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-your-code-to-a-new-edition.html#fix-edition-compatibility-warnings)
> Update to Rust edition 2018.

- Cargo.toml
This PR removes the cargo edition feature specification. 
It is now marked as stable by Cargo, so it can be removed from the Cargo.toml
> Remove cargo feature: edition

- src/config.rs
- src/main.rs
- src/operations/transformations.rs
- src/processor/conversion.rs
- src/processor/encoding_format.rs
Some clap options/flags do not require an output file to be given as argument.
By including the output path directly in the config, an output path was always required.
This commit makes Config.output an Option, so that one can be provided
if required, but also None can be given.
> Fix bug where output was always required to be constructed in the Config.

- docs/cli_help_script_unsharpen.txt
- tests/cli_convert.rs
- tests/cli_license.rs
- tests/cli_user_manual.rs
See the attached issue.
--- 
Issue: #71
> Add user tests

- .travis.yml
- README.md
- RELEASE_STEPS.md
- src/config.rs
- src/lib.rs
This PR makes it possible to use the Rust stable channel by removing the `range_contains` feature, which is only available on the Rust nightly release channel.
A Rust version 1.31 compiler with Rust edition 2018 is required as of now.
This is not tested in the TravisCI as of this PR. Perhaps it should?
Or should just the latest stable version be required?
--- 
Issue: #79
> Move to Rust stable release channel from nightly.

- Cargo.lock
- Cargo.toml
- RELEASE_STEPS.md
Rerelease the 0.8.0 version (but with a new version number) now it is compatible with a stable compiler release.
- Should the version number be 0.8.1 or 0.9.0
- In case of 0.9.0, need to shift all planned features by one.
decided: 0.8.1 since no breaking changes are made for a user
-- 
issue: #82
> Publish stable compatible version 

- src/operations/grammar.pest
- src/operations/mod.rs
- src/operations/parse.rs
- src/operations/transformations.rs
Syntax:
- `crop LX LY RX RY`
- LX is Left top corner X coordinate starting at 0
- LY is Left top corner Y coordinate starting at 0
- RX is Right bottom corner X coordinate 
- RY is Right bottom corner Y coordinate 
Invariants:
`RX > LX` and `RY > LY`
- if `>=` then 0 pixel axis' would be allowed.
Questions:
- What 2D coordinate system does the `image` crate use? / Where is x=0,y=0?
> top left is (0,0)
--
issue: #64
> image operation: crop

- README.md
- docs/cli_help_script.txt
- src/operations/grammar.pest
- src/operations/mod.rs
- src/operations/parse.rs
Makes the `;` separator a requirement, for improved reading clarity. 
---
issue: #86
> Require separators between operations.

- .travis.yml
- Cargo.lock
- Cargo.toml
- sic_core/Cargo.toml
- sic_core/src/lib.rs
- sic_image_engine/Cargo.toml
- sic_image_engine/src/engine.rs
- sic_image_engine/src/lib.rs
- sic_image_engine/src/test_includes.rs
- sic_image_engine/src/wrapper/filter_type.rs
- sic_image_engine/src/wrapper/mod.rs
- sic_parser/Cargo.toml
- sic_parser/src/lib.rs
- sic_parser/src/rule_parser.rs
- src/app/run_mode.rs
- src/main.rs
Enables faster changes by being able to use workspace crates and therefore depend on the workspace crate path instead of a published version. 
Sets travis ci to use 'cargo test' and 'cargo build' with the '--all'
flag to build and test the full workspace.
closes #126 
---
issue: #126 
tracking issue: #125
> Re-integrate combostew as sub crate: image engine.

- Cargo.lock
- Cargo.toml
- sic_config/Cargo.toml
- sic_config/src/lib.rs
- sic_core/Cargo.toml
- sic_core/src/lib.rs
- sic_io/Cargo.toml
- sic_io/src/conversion.rs
- sic_io/src/encoding_format.rs
- sic_io/src/lib.rs
- sic_parser/src/rule_parser.rs
- sic_testing/Cargo.toml
- sic_testing/src/lib.rs
- src/app/cli.rs
- src/app/custom_config.rs
- src/app/license_display.rs
- src/app/mod.rs
- src/app/run_mode.rs
- tests/cli_convert.rs
* combostew: io => `sic_io`
* combostew: config => `sic_config`
* combostew: processor:
* license_display => `sic_lib`
* mod_test_includes => `sic_testing`
* conversion => `sic_io`
* encoding_format => `sic_io`
Additionally, ProcessWithConfig was not ported over.
Modules which depended on it were slightly changed to accommodate for
this change.
This change set does not included further refactorings like
removing unnecessary dependencies on the sic_config crate.
closes #129
> Re-integrate combostew as sub crates: config, conversion+io, testing.

- README.md
- docs/cli_help_script.txt
- docs/cli_help_script_blur.txt
- docs/cli_help_script_brighten.txt
- docs/cli_help_script_contrast.txt
- docs/cli_help_script_filter3x3.txt
- docs/cli_help_script_huerotate.txt
- docs/cli_help_script_resize.txt
- docs/cli_help_script_unsharpen.txt
- sic_parser/src/grammar.pest
- sic_parser/src/rule_parser.rs
* Accept floating point numbers for blur, instead of uint.
* The lowered code did work with f32 already.
closes #130
> Fix pest grammar, which accepted blur with uint instead of fp.

- Cargo.lock
- Cargo.toml
- build.rs
- src/app/license_display.rs
- src/app/run_mode.rs
The current executable size is quite big. One thing which increases the executable size is the DEP_LICENSES file, which is distributed with every build. Some licenses of deendencies we use require this and for others: it is only fair to attribute these authors.  
This file contains huge amounts of duplication (because many dependencies use
the same licenses), thus is likely to have a good compression ratio.
This PR compresses the DEP_LICENSES file on compile time. Then (still on compile time) the resulting compressed bytes are included in the executable. At runtime, if `--dep-licenses` is used, we uncompress the license text and show it. 
If this doesn't reduce the binary enough (but how much is enough?), another option might be to provide the release
binaries within a zip file, which …
> Reduce executable size: compress the included dependency licenses text. 

- Cargo.lock
Instead of having dependabot update these lockfile dependencies one by one, this PR updates them all at once.
> Update lockfile dependencies.

- sic_image_engine/src/engine.rs
Resolve warning on taking reference of vector instead of slice
fixes #187
> change type signature of ignite fn  statements parameter

- Cargo.toml
- components/sic_image_engine/Cargo.toml
- components/sic_io/Cargo.toml
- components/sic_parser/Cargo.toml
- components/sic_testing/Cargo.toml
This way, we can use the in development version locally,
while not having to replace the path with a version number when
publishing the crate.
> Add a version in addition to the path for dependencies of components.

- Cargo.lock
- Cargo.toml
- components/sic_image_engine/Cargo.toml
- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/errors.rs
- components/sic_image_engine/src/lib.rs
- components/sic_image_engine/src/wrapper/filter_type.rs
- components/sic_io/Cargo.toml
- components/sic_io/src/conversion.rs
- components/sic_io/src/errors.rs
- components/sic_io/src/format.rs
- components/sic_io/src/lib.rs
- components/sic_io/src/load.rs
- components/sic_io/src/save.rs
- components/sic_parser/Cargo.toml
- components/sic_parser/src/errors.rs
- components/sic_parser/src/lib.rs
- components/sic_parser/src/rule_parser.rs
- components/sic_parser/src/value_parser.rs
- src/app/cli.rs
- src/app/config.rs
- src/app/license.rs
- src/app/operations.rs
- src/app/procedure.rs
- src/main.rs
- tests/cli_convert.rs
- tests/cli_image_operation_args.rs
This PR replaces custom enum based errors, String errors (majority) and Box<dyn Error> based error handling.
The majority of the code based used to use string based
error handling. Strings are not great for error handling since they
prevent many diagnostic decorations.
If we were to use the std library error handling we would be implementing
std::error::Error and std::fmt::Display (and sometimes std::convert::From).
This can quickly become a verbose task, but it is also straightforward,
easy to maintain and works well for compatibility.
To reduce verbosity I've selected the thiserror crate which is compatible
with the std library method. This crate provides attribute macros which
help with implementing Display, Error and From amongst others.
The bin part of the project will use the anyhow …
> Replace custom, String based and casted error handling with anyhow and thiserror crates.

- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/wrapper/filter_type.rs
Lanczos3 produces subjectively an improved image quality (mostly sharper) compared to the current default, which uses a Gaussian filter.
According to a single test case located in the image docs [1], Lanczos3 would have a similar computing cost compared a Gaussian filter. This cost is relatively higher than nearest neighbor, triangle or a Catmull-Rom filter, but produces subjectively the best quality images. For now we will opt to use the "highest available quality" and we can use the resize_sampling_filter option to use another filter if so desired (for example if the computing cost would be too high).
Admittedly, this switch is based on some subjectivity and assumptions. We should aim to test, benchmark and properly study these sampling filters in the future.
[1] …
> Set the default sampling filter for resize to Lanczos3.

- Cargo.lock
- components/sic_cli_ops/Cargo.toml
- components/sic_cli_ops/src/errors.rs
- components/sic_cli_ops/src/lib.rs
- components/sic_cli_ops/src/operations.rs
Previously we used anyhow, because this module was split (to its own library) from the binary crate.
closes #364
> Port error handling of sic_cli_ops to thiserror.

- components/sic_cli/src/cli.rs
- components/sic_cli/src/config.rs
- components/sic_cli/src/pipeline.rs
- src/main.rs
- tests/cli_convert.rs
This commit removes ArgMatches as an argument of pipeline::run. The aim is that it will enable us in the future
to run the pipeline in parallel with different inputs/outputs (which now becomes possible by setting the config
in- and output to different values, e.g. by allowing the input and output cli arguments to take multiple values).
This is an intermediate step, so we don't need to refactor and optimize the whole pipeline just yet.
> pipeline::run depended on both argmatches and config while it should only use locally known data

- src/cli/app.rs
- src/main.rs
The main advantage is that it puts focus on just the argument name and one doesn't need to manually supply a static str value.
> Use a macro to define new arguments

- src/cli/app.rs
- src/cli/config.rs
- src/cli/pipeline/fallback.rs
- src/cli/pipeline/mod.rs
- src/lib.rs
- tests/cli_output_format_decider_fallback.rs
The `image` crate has a convenient built in way to determine the format which could be used for an output path called `ImageFormat::from_path`. It determines based on an extension, what format an image should be. `sic` has (for various reasons) its own, but similar,  built in way to handle the above problem. The disadvantage of using our own version is that for each added output format (by the same `image` crate 😄), we need to add an option to our image format decider to support the new format. In addition, we do currently not always support the same extensions/identifiers (e.g. farbfeld is supported by `sic` using the extension `farbfeld`, while the `image` crate also allows for `ff`).  This PR allows to fallback to the output format decider as supplied by the image crate _if_ `sic's` …
> Add an (direct) image crate output format decider fallback option

- components/sic_cli_ops/src/lib.rs
- components/sic_image_engine/src/errors.rs
- components/sic_parser/src/errors.rs
- components/sic_parser/src/rule_parser.rs
- components/sic_parser/src/value_parser.rs
- Trick was used because I (wrongly) thought I always received a string with quotation marks from my pest parser
- This was not true, I forgot to go one level deeper in the pairs iterator
- This PR removes the trick
closes #431
> Refactor quotation mark trick for ImageFromPath: remove trick because it's unnecessary

- Cargo.lock
- Cargo.toml
- components/sic_cli_ops/Cargo.toml
- components/sic_cli_ops/src/errors.rs
- components/sic_cli_ops/src/lib.rs
- components/sic_cli_ops/src/operations.rs
- components/sic_image_engine/src/engine.rs
- components/sic_image_engine/src/lib.rs
- components/sic_image_engine/src/wrapper/draw_text_inner.rs
- components/sic_image_engine/src/wrapper/mod.rs
- components/sic_io/src/conversion.rs
- components/sic_parser/src/errors.rs
- components/sic_parser/src/grammar.pest
- components/sic_parser/src/named_value.rs
- components/sic_parser/src/rule_parser.rs
- components/sic_parser/src/value_parser.rs
- src/cli/app.rs
- tests/cli_imageproc_ops.rs
Adds the `draw-text` operation to the cli ops parser. The operation and script parser for `draw-text [..]` have been implemented before, and can be found in #426  (issue #335). The syntax for the `draw-text` arguments will be equal to the syntax used by the script parser, i.e. `--draw-text 'example' 'coord(0,1)' 'rgba(0,0,0,255)' 'size(24)' font("<path>")`. 
closes #434
> Add draw-text image operation as cli operation

- README.md
- src/cli/app.rs
- src/cli/common_dir.rs
- src/cli/config.rs
- src/cli/glob_base_dir.rs
- tests/cli_glob.rs
- tests/cli_image_operation_args.rs
- tests/cli_image_operations_script_from_file.rs
- tests/cli_imageproc_ops.rs
- tests/cli_output_format_decider_fallback.rs
- tests/common/mod.rs
> Refactor io mode user interface

- deny.toml
It involves a dependency of a dependency, and we'll have to wait until the imageproc dependency we rely on is updated. Note that imageproc is only built when building sic with the 'imageproc-ops' feature.
Note that this "temp. fix" only ensures that the CI will succeed again, since we added the advisory to the ignore list. The issue itself is not solved and #567 will still be kept open. 
closes #572
> Ignore RUSTSEC-2020-0023 advisory for now

- LICENSE-APACHE
- NOTICE
- README.md
This applies solely to my own contributions (the majority), and only to the sic source code and combined work. Contributions prior to 2020-10-04 will be used under the MIT license. Binaries will still be distributed under the MIT license. The change is mainly to reflect the wish to add a more explicit definition for contributions by third parties.
> Re-license my contributions to MIT/Apache-2.0 license

- components/sic_io/src/conversion.rs
- components/sic_io/src/format.rs
Now ImageOutputFormat support for AVIF was incorporated by image, and we updated our image dependency version, we don't need this hack anymore.
> Remove AVIF ImageOutputFormat hack

- .github/workflows/ci.yml
- components/sic_image_engine/src/lib.rs
- components/sic_parser/src/lib.rs
- tasks/publish/src/main.rs
- tests/cli_convert.rs
- tests/cli_glob.rs
- tests/cli_image_operation_args.rs
We explicitly allow the newly enabled clippy::unnecessary_wraps lint. Although the lint has good intentions, we disable it because it decreases code readability of the caller functions.
relevant issues:
* https://github.com/rust-lang/rust-clippy/issues/6726
* https://github.com/rust-lang/rust-clippy/issues/6721
> Fix Rust 1.50 linter issues

- .github/workflows/ci.yml
- Cargo.lock
- deny.toml
- justfile
An advisory was published for a downstream dependency on rand_core, which made our pipeline fail. This commit updates the lock file so our dependencies will rely on a version which includes the fix for the vulnerability addressed by the advisory.
> Update lock file to account for RUSTSEC-2021-0023

- components/sic_cli_ops/src/lib.rs
- components/sic_io/src/lib.rs
- components/sic_parser/src/lib.rs
This lint was added in Rust Clippy v1.51, but requires changes in public API's. This isn't a huge problem for `sic`, but whether this lint is good or not is an opinionated affair which I don't want to dip into right now.
> Allow the upper_case_acronyms lint

- deny.toml
- tests/common/mod.rs
* We're waiting for chrono to update
* We may want to update to time 0.3, and have this replace chrono
* Presumably very difficult to exploit the vulnerability, so not too high a risk
> Add the two `time` rustsec advisories to the exception list

- deny.toml
There are no known vulnerabilities, and the dependency is not doing magic, so
until it has been replaced down-tree (there's an open PR for a few days), it should
be find, and non-blocking. To be revisited after it has been patched out down-tree.
> Allow unmaintained crate ansi_term for now

- deny.toml
- No known security issues
- Requires update from imageproc. no patch yet
- ab_glyph replacement is available
> Rusttype is unmaintained

- src/cli/app.rs
- src/cli/config.rs
Previously we would explicitly require the --input or --glob-input argument to be present, for the input mode to be selected (batch or single file input and output).
Now we instead check if --glob-input is present, and if it is select batch mode, otherwise we always select 'simple' mode (i.e. single input and output). NB: this also means that stdin should always use single input and output.
fixes #1398
> Fix issue where image could not be loaded from stdin

- .github/workflows/build-release-binaries.yml
sic was renamed to imagineer, but this workflow should reflect that
> Fix build-release-binaries.yml post-rename
